[package]
name = "fastformat"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Fast world data converter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fastformat"
crate-type = ["cdylib", "lib"]

[dependencies]
pyo3 = "0.21.1"
ndarray = "0.15.4"
arrow = "52.1.0"
eyre = "0.6.12"
