[package]
name = "dummy-opencv-capture"
version.workspace = true
edition.workspace = true
documentation.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arrow = { workspace = true }
